<a href="https://colab.research.google.com/github/codehacker4655/codehacker4655/blob/main/PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
#creating tensor
tensor0=torch.tensor(1)#scalar
tensor0

tensor(1)

In [ ]:
tensor0.ndim#to know the dimension of tensor

0

In [ ]:
tensor1=torch.tensor([1,2,3,4])#1 dimmension
print(tensor1.ndim)
tensor2=torch.tensor([[1,2,3],[4,5,6]])
print(tensor2.ndim) #2 dimmension

1
2


In [ ]:
print(tensor2)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
print(tensor1)#one dimension
print(tensor2)#two dimension
print(tensor1.ndim)
print(tensor1.dim())
print(tensor2.ndim)
print(tensor1.dim())
print(tensor0.shape)
print(tensor1.size())
print(tensor2.shape)
print(tensor2.size())


tensor([1, 2, 3, 4])
tensor([[1, 2, 3],
        [4, 5, 6]])
1
1
2
1
torch.Size([])
torch.Size([4])
torch.Size([2, 3])
torch.Size([2, 3])


In [ ]:
size=(3,4)#returns a intialised values like garbage values
tensor4=torch.empty(size)
print(tensor4)

tensor([[3.3631e-44, 1.7859e+31, 3.1098e-37, 4.3642e-41],
        [1.4013e-45, 2.7370e+20, 5.7819e-34, 0.0000e+00],
        [5.6052e-45, 8.4078e-45, 5.6052e-45, 1.8217e-44]])


In [ ]:
tensor5=torch.rand(size)
tensor5#it will generate he values between 0 and 1

tensor([[0.6984, 0.1653, 0.4040, 0.3978],
        [0.6266, 0.4584, 0.3901, 0.5618],
        [0.3124, 0.2722, 0.4921, 0.2745]])

In [ ]:
tensor6=torch.zeros(size)
tensor6

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
tensor7=torch.ones(size)
tensor7

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor8=torch.rand(1,2)
tensor8
tensor8.dtype

torch.float32

In [ ]:
#creating tensor with a specific datatype
tensor9=torch.rand(1,2,dtype=torch.float64)
print(tensor9)

tensor([[0.6403, 0.7393]], dtype=torch.float64)


In [ ]:
tensor8.type(torch.double)#to double the size from float32 to float64

tensor([[0.0118, 0.8421]], dtype=torch.float64)

In [ ]:
#converting numpy to tensor
import numpy as np
example_array=np.array([[9,3],[0,4]])
tensor8=torch.from_numpy(example_array)
print(tensor8)

tensor([[9, 3],
        [0, 4]])


In [ ]:
tensor9=torch.tensor(example_array)
print(tensor9)

tensor([[9, 3],
        [0, 4]])


In [ ]:
example_array*=3
print(tensor8)#here when we use from_numpy the changes u made in that will be reflected in all tensors
print(tensor9)#here there will be no change

tensor([[27,  9],
        [ 0, 12]])
tensor([[9, 3],
        [0, 4]])


In [ ]:
#creating a tensor from another tensor
tensor10=torch.ones_like(tensor9)
print(tensor10)#it will take the shape and datatype of the tensor

tensor([[1, 1],
        [1, 1]])


In [ ]:
#device configiration
device=torch.device("cuda" if torch.cuda.is_available() else 'cpu')#keeping our device to gpu
tensor11=torch.ones(3,7).to(device)#changing the device location from gpu to cpu
tensor11=torch.zeros(3,7,device=device)

In [ ]:
#accessung elements in tensor
print(tensor2)
print(tensor2.dim())
print(tensor2.size())
print(tensor2[0])

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
tensor([1, 2, 3])


In [ ]:
tensor2[1,0]

tensor(4)

In [ ]:
tensor2[:,2]

tensor([3, 6])

In [ ]:
tensor2[0,:]

tensor([1, 2, 3])

In [ ]:
tensor12=torch.ones(2,3)
tensor13=torch.rand(2,3)

In [ ]:
tensor14=tensor12+tensor13
print(tensor14)
tensor15=torch.add(tensor12,tensor13)
tensor16=tensor12-tensor13
print(tensor16)
tensor17=torch.sub(tensor12,tensor13)
tensor18=tensor12*tensor13
print(tensor18)
tensor19=torch.mul(tensor12,tensor13)

tensor([[1.6162, 1.6350, 1.3827],
        [1.9541, 1.3987, 1.1817]])
tensor([[0.3838, 0.3650, 0.6173],
        [0.0459, 0.6013, 0.8183]])
tensor([[0.6162, 0.6350, 0.3827],
        [0.9541, 0.3987, 0.1817]])


In [ ]:
x=torch.randint(0,3,(4,5))#(low,high,(shape))
x

tensor([[1, 0, 1, 1, 2],
        [0, 0, 2, 2, 1],
        [2, 1, 2, 2, 2],
        [0, 0, 2, 0, 0]])

In [ ]:
y=x.view(20)#resizing the shape to one dimension
z=x.view(-1,10)#resizing the shape in 2d form where it can figure out the shapes
print(y)
print(z)
print(x.size(),y.size(),z.size())

tensor([1, 0, 1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0])
tensor([[1, 0, 1, 1, 2, 0, 0, 2, 2, 1],
        [2, 1, 2, 2, 2, 0, 0, 2, 0, 0]])
torch.Size([4, 5]) torch.Size([20]) torch.Size([2, 10])


In [ ]:
a=torch.arange(9)#a tensor will get created from numberszero to nine
a=a.reshape(3,3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
b=torch.randint(0,9,(3,3))##(low,high,size)
b

tensor([[0, 1, 0],
        [5, 5, 5],
        [6, 1, 1]])

In [ ]:
c=torch.cat((a,b),dim=1)#adding elememnts in dimension way
c

tensor([[0, 1, 2, 0, 1, 0],
        [3, 4, 5, 5, 5, 5],
        [6, 7, 8, 6, 1, 1]])

In [ ]:
d=torch.cat((a,b),dim=0)
d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 0],
        [5, 5, 5],
        [6, 1, 1]])

In [ ]:
p=torch.randint(0,9,(2,3,5))
p

tensor([[[6, 3, 1, 0, 6],
         [3, 4, 5, 6, 5],
         [1, 0, 7, 2, 2]],

        [[4, 7, 7, 5, 8],
         [0, 3, 6, 3, 7],
         [7, 8, 5, 4, 2]]])

In [ ]:
p.sum()

tensor(127)

In [ ]:
p.sum(dim=0)

tensor([[10, 10,  8,  5, 14],
        [ 3,  7, 11,  9, 12],
        [ 8,  8, 12,  6,  4]])

In [ ]:
p.sum(dim=1).shape

torch.Size([2, 5])

In [ ]:
p.sum(dim=2).shape

torch.Size([2, 3])

In [ ]:
#Autograd(to compute the gradients)
import torch
x=torch.tensor(2.0)
x.requires_grad,x.is_leaf


(False, True)

In [ ]:
y=3*torch.sigmoid(x)+5
y.requires_grad,y.is_leaf

(True, False)

In [ ]:
x=torch.tensor(2.0,requires_grad=True)#and when you set this it will have track of all computations which means in the flow whatever we have we get the value true cause we are caluclating the gradients to use in the chain rule of derivaties
y=3*torch.sigmoid(x)+5
print(y.requires_grad,y.is_leaf)#so to caluaclate the gradients require_grad must be true cause it only caluclates the derivative and the x shpuld be leaf so that it can save derivaties
print(x.requires_grad,x.is_leaf)
#time_stamp-34:06

True False
True True


In [ ]:
y.backward()#this caluclates the gradient
print(x.grad)

tensor(0.3150)


In [ ]:
x.grad.zero_()#to set back to zero
y=3*torch.sigmoid(x)+5
y.backward()
x.grad

tensor(0.3150)

In [ ]:
a=torch.rand(2,5,requires_grad=True)


In [ ]:
b=a*a+a+5
b

tensor([[5.4660, 6.0409, 5.9647, 5.9738, 6.6969],
        [5.8095, 5.9632, 5.0048, 5.1443, 5.2927]], grad_fn=<AddBackward0>)

In [ ]:
c=b.mean()
c

tensor(5.7357, grad_fn=<MeanBackward0>)

In [ ]:
b.retain_grad()

In [ ]:
c.backward()
print(a.grad)
print(b.grad)

tensor([[0.1692, 0.2272, 0.2204, 0.2213, 0.2791],
        [0.2059, 0.2203, 0.1010, 0.1256, 0.1473]])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])


In [ ]:
x=torch.linspace(0.0,1.0,15)
w=torch.tensor([5])
b=torch.tensor([3])
y=w*x+b
y

tensor([3.0000, 3.3571, 3.7143, 4.0714, 4.4286, 4.7857, 5.1429, 5.5000, 5.8571,
        6.2143, 6.5714, 6.9286, 7.2857, 7.6429, 8.0000])

In [ ]:
w=torch.randn(size=(1,1),requires_grad=True)
b=torch.randn(size=(1,1),requires_grad=True)

def forward(x):
  return w*x+b
def loss(y,y_pred):
  return((y_pred-y)**2).mean()
print('w',w)
print('b',b)


w tensor([[0.0707]], requires_grad=True)
b tensor([[1.5195]], requires_grad=True)


In [ ]:
learning_rate=0.03
num_epochs=180
#train the model
for epoch in range(num_epochs):
  y_pred=forward(x)
  l=loss(y,y_pred)
  l.backward()
  with torch.no_grad():
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
  w.grad.zero_()
  b.grad.zero_()
  if (epoch+1)%10==0:
    print(f'epoch {epoch+1}:w={w.item()},loss={l.item()}')


epoch 10:w=1.1606858968734741,loss=4.966108322143555
epoch 20:w=1.7249176502227783,loss=1.6638877391815186
epoch 30:w=2.048062324523926,loss=0.9317092895507812
epoch 40:w=2.2591052055358887,loss=0.7307809591293335
epoch 50:w=2.4165549278259277,loss=0.6430671215057373
epoch 60:w=2.5470194816589355,loss=0.5825576782226562
epoch 70:w=2.662660598754883,loss=0.5312888026237488
epoch 80:w=2.7690978050231934,loss=0.48526498675346375
epoch 90:w=2.8689846992492676,loss=0.44337838888168335
epoch 100:w=2.9636263847351074,loss=0.4051383137702942
epoch 110:w=3.053715229034424,loss=0.37020251154899597
epoch 120:w=3.139660358428955,loss=0.33828064799308777
epoch 130:w=3.221738338470459,loss=0.309111624956131
epoch 140:w=3.3001623153686523,loss=0.2824579179286957
epoch 150:w=3.3751132488250732,loss=0.2581023573875427
epoch 160:w=3.4467523097991943,loss=0.23584716022014618
epoch 170:w=3.515230178833008,loss=0.21551069617271423
epoch 180:w=3.580688238143921,loss=0.19692783057689667


In [1]:
import torch
import torch.nn as nn#layers,activation functions
import torch.optim as optim#optimisers

from torchvision import datasets,transforms#to change the image to text

In [2]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
#hyper parameter tunning
hidden_size=400
num_epochs=8
batch_size=32
learning_rate=0.01


In [4]:
train_dataset=datasets.MNIST(root='data',train=True,transform=transforms.ToTensor(),download=True)#will be converting the image to tensor and also we will downloading 60,000 images
test_dataset=datasets.MNIST(root='data',train=False,transform=transforms.ToTensor(),download=True)#it will load the test dataset

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 9.91M/9.91M [00:00<00:00, 17.3MB/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 28.9k/28.9k [00:00<00:00, 485kB/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 1.65M/1.65M [00:00<00:00, 4.39MB/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 4.54k/4.54k [00:00<00:00, 13.0MB/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [5]:
print(train_dataset.classes)#to know the classes
print(train_dataset.data.shape)#to know number of images and size of each image
print(train_dataset.targets.shape)

['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
torch.Size([60000, 28, 28])
torch.Size([60000])


In [6]:
print(test_dataset.classes)
print(test_dataset.data.shape)
print(test_dataset.targets.shape)

['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
torch.Size([10000, 28, 28])
torch.Size([10000])


In [7]:
#size we givein and expect as output
in_features=784
out_features=10

In [8]:
train_dataloader=torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)
test_dataloader=torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=False)


In [9]:
import matplotlib.pyplot as plt
data=iter(train_dataloader)
imgs,label=next(data)
print(imgs.shape)
print(label.shape)
#some math

torch.Size([32, 1, 28, 28])
torch.Size([32])


In [10]:
class basicneuralnetwork(nn.Module):
  def __init__(self,hidden_size):
    super(basicneuralnetwork,self).__init__()
    self.hidden_size=hidden_size
    self.layer1=nn.Linear(in_features,self.hidden_size)
    self.layer2=nn.Linear(self.hidden_size,out_features)

  def forward(self,x):
    out=self.layer1(x)
    out=torch.relu(out)
    out=self.layer2(out)
    return out

model=basicneuralnetwork(hidden_size).to(device)


In [11]:
w1,b1,w2,b2=list(model.parameters())
print(w1,b1,w2,b2)

Parameter containing:
tensor([[-0.0352,  0.0079,  0.0352,  ..., -0.0213,  0.0187,  0.0008],
        [ 0.0008, -0.0288, -0.0194,  ...,  0.0076,  0.0215, -0.0252],
        [ 0.0078, -0.0130,  0.0159,  ..., -0.0138,  0.0112, -0.0008],
        ...,
        [ 0.0195, -0.0314,  0.0339,  ..., -0.0246,  0.0091, -0.0287],
        [ 0.0065, -0.0137, -0.0090,  ..., -0.0302,  0.0180,  0.0279],
        [ 0.0324, -0.0221, -0.0256,  ...,  0.0301,  0.0292, -0.0165]],
       device='cuda:0', requires_grad=True) Parameter containing:
tensor([ 3.4120e-02,  3.4474e-02, -1.6432e-02, -1.1041e-02,  2.9989e-02,
         2.7629e-02, -2.1341e-03,  3.4606e-03, -3.3878e-02, -1.3674e-02,
         4.1660e-03, -1.9481e-02, -2.2283e-02, -3.4049e-02, -1.8553e-02,
         2.0453e-02, -8.6869e-03,  1.0377e-02,  2.3788e-02,  1.9679e-02,
        -2.8805e-02,  2.0694e-02, -2.6331e-02, -1.9587e-03, -2.4594e-02,
        -2.7361e-02, -1.5762e-02, -1.1172e-02, -1.4734e-02,  2.3327e-02,
        -2.4738e-02, -7.5683e-03, -1.717

In [12]:
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=learning_rate)

In [13]:
#training
total_steps=len(train_dataloader)#to know number of iterations
for epoch in range(num_epochs):#here we are defining the epochs
  for i,(images,labels) in enumerate(train_dataloader):#batch index,and images and their corresponding labels at every batch 32 images will be loading as input
    images=images.reshape(-1,28*28).to(device)#will be reshaped to 784 size so that it satisfies the input features
    labels=labels.to(device)

    outputs=model(images)#output for 32 images inform of tensors

    loss=criterion(outputs,labels)#now it caluclates the loss for the 32 samples according to the formula and takes the average value of it

    loss.backward()#here we compute dl/dw,dw/db

    optimizer.step()#it updates the weights according to learning rate and gradients and update all parameters for every batch

    optimizer.zero_grad()
    if (i+1)%100==0:
      print(f'epoch {epoch+1}/{num_epochs},step {i+1}/{total_steps},loss={loss.item():.4f}')


epoch 1/8,step 100/1875,loss=0.1640
epoch 1/8,step 200/1875,loss=0.1892
epoch 1/8,step 300/1875,loss=0.0984
epoch 1/8,step 400/1875,loss=0.4569
epoch 1/8,step 500/1875,loss=0.2165
epoch 1/8,step 600/1875,loss=0.3384
epoch 1/8,step 700/1875,loss=0.1416
epoch 1/8,step 800/1875,loss=0.4008
epoch 1/8,step 900/1875,loss=0.0155
epoch 1/8,step 1000/1875,loss=0.1192
epoch 1/8,step 1100/1875,loss=0.1269
epoch 1/8,step 1200/1875,loss=0.1396
epoch 1/8,step 1300/1875,loss=0.0644
epoch 1/8,step 1400/1875,loss=0.2284
epoch 1/8,step 1500/1875,loss=0.0899
epoch 1/8,step 1600/1875,loss=0.0256
epoch 1/8,step 1700/1875,loss=0.1281
epoch 1/8,step 1800/1875,loss=0.2287
epoch 2/8,step 100/1875,loss=0.0401
epoch 2/8,step 200/1875,loss=0.1956
epoch 2/8,step 300/1875,loss=0.0628
epoch 2/8,step 400/1875,loss=0.4703
epoch 2/8,step 500/1875,loss=0.1049
epoch 2/8,step 600/1875,loss=0.2159
epoch 2/8,step 700/1875,loss=0.0530
epoch 2/8,step 800/1875,loss=0.1421
epoch 2/8,step 900/1875,loss=0.1477
epoch 2/8,step 1000

In [14]:
#testing and accuracy part left